# DEFAULT
spring:
  profiles:
    active: "local"
  resources:
    static-locations: classpath:/static/
  logging:
    file: logs/application.log
    pattern:
      console: "%d %-5level %logger : %msg%n"
      file: "%d %-5level [%thread] %logger : %msg%n"
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      # ddl-auto: create-drop
      ddl-auto: none
      use-new-id-generator-mappings: false
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
---
# LOCAL
spring:
  profiles: local
  logging:
    level:
      org.springframework.web: DEBUG
      guru.springframework.controllers: DEBUG
      org.hibernate: DEBUG
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: false
  datasource:
    url: jdbc:mysql://localhost:3306/swagger?useUnicode=true&characterEncoding=utf8
    username: swagger
    password: swagger

swagger:
  base:
    url: /
---
# DEV
spring:
  profiles: dev
  logging:
    level:
      org.springframework.web: DEBUG
      guru.springframework.controllers: DEBUG
      org.hibernate: DEBUG
---
# BETA
spring:
  profiles: beta
  logging:
    level:
      org.springframework.web: DEBUG
      guru.springframework.controllers: DEBUG
      org.hibernate: DEBUG
---
# PRODUCTION
spring:
  profiles: prod
  logging:
    level:
      org.springframework.web: INFO
      guru.springframework.controllers: INFO
      org.hibernate: INFO